__include__: ['ecdet_l_dinov2s_eomt_liver_363_100e_es10.yml']

output_dir: outputs/ablation/ecdet_l_dinov2s_ecl_o365_decoderbody_breast_363_100e_es20
num_classes: 4
remap_mscoco_category: false
early_stop_patience: 20

train_dataloader:
  total_batch_size: 32
  dataset:
    img_folder: /cobot/Data/Lesion_det/det_breast/img
    ann_file: /cobot/Data/Lesion_det/det_breast/annotations/Lesion/Ignore_Delete-Image/train.json

val_dataloader:
  total_batch_size: 32
  dataset:
    img_folder: /cobot/Data/Lesion_det/det_breast/img
    ann_file: /cobot/Data/Lesion_det/det_breast/annotations/Lesion/Ignore_Delete-Image/valid.json
