__include__: ['ecdet_l_dinov2s_breast_cmp5L_kq_15e_base.yml']
output_dir: outputs/ablation/cmp5L_shared_query_kd/KQ2
shared_query_kd:
  enabled: true
  teacher_memory_mode: privileged_np
  layers: [0, 1, 2, 3]
