__include__: ['ecdet_l_dinov2s_breast_cmp5L_kq2.yml']

output_dir: outputs/ablation/cmp5L_shared_query_kd/debug_kq2_amp_ddp_v1
epochs: 1
early_stop_patience: 1
checkpoint_interval_steps: 0
print_freq: 1

train_dataloader:
  total_batch_size: 2
  num_workers: 0
  shuffle: false
  drop_last: false
  dataset:
    ann_file: /cobot/Code/wanrui/EdgeCrafter/outputs/ablation/cmp5L_qg_query_selection_behavior_distillation/stage1_full640_subset_v1.json

val_dataloader:
  total_batch_size: 2
  num_workers: 0
  dataset:
    ann_file: /cobot/Code/wanrui/EdgeCrafter/outputs/ablation/cmp5L_qg_query_selection_behavior_distillation/stage1_full640_subset_v1.json
