__include__: [
  'ecdet_x_mae_dino_vitb_liver_363_50e.yml',
]

output_dir: outputs/ablation/ecdet_x_mae_dino_vitb_liver_layerwise363_633_50e

ECTransformer:
  num_points: [[3, 6, 3], [6, 3, 3], [6, 3, 3], [3, 6, 3]]
