__include__: [
  'ecdet_l_dinov2s_patch16_dec3_liver.yml',
]

output_dir: outputs/ablation/ecdet_l_dinov2s_patch16_dec3_liver_no_go_ddf

# Keep FDR/FGL, but use layer-local matching and remove final-to-aux DDF.
ECCriterion:
  use_uni_set: false
  use_fgl: true
  use_ddf: false
